### ISSUE TITLE
AttributeError: 'MinkowskiConvolution' object has no attribute 'dimension'

### ISSUE THREAD

**Issue by HengDora** [rayguan97/crossloc3d#1]
I encountered an issue while trying to run the project's main.py script. When I attempted to run the script using the following command:
`python main.py ./configs/campus_ours.py`

I received the following error message:
`AttributeError: 'MinkowskiConvolution' object has no attribute 'dimension'`

Issue Description:

While running the script, I encountered an AttributeError error, and the error message pointed to the dimension attribute of the MinkowskiConvolution class. Based on my understanding, this attribute should exist, but in my execution, it appears to be undefined. I reviewed the project's documentation and code but couldn't find any apparent issues.

[https://github.com/NVIDIA/MinkowskiEngine/issues/366](url) and [https://github.com/NVIDIA/MinkowskiEngine/issues/264](url)
These 2 links also mentioned this problem. How did you solve it?

I'd like to extend my gratitude for your outstanding work and dedication.

Thank you for your time and consideration.

Best regards,
HengDora

**Comment by rayguan97** [comment]
Hi,

I remember I run into this issue before. I think you might have to use a specific version of minkoswkiengine (0.5.4). Also there are issues with running it on multiple gpus. 

Could you share more details? Including how many and which gpus are you using, the package version of minkoswkiengine. Did you follow the instruction exactly? Did you modify the config?

Meanwhile I will take a look into this issue and try to reproduce it from my end.

Best,
Tianrui

**Comment by aswathselvam** [comment]
Hi @HengDora, please try using single GPU training as quick fix, it works for me:
`CUDA_VISIBLE_DEVICES=0 python main.py ./configs/campus_ours.py`

**Comment by HengDora** [comment]
@aswathselvam Thank you very much for your eagerness to help, it works for me too!

**Comment by HengDora** [comment]
@rayguan97 Thank you very much for your response. I followed [the steps you provided](https://github.com/rayguan97/crossloc3d#setting-up-environment) for setting up the environment exactly. Here are the specific steps:

```bash
# Create and activate a virtual environment
conda create -n crossloc python=3.7 pandas tensorboard numpy -c conda-forge
conda activate crossloc

# Install PyTorch and related dependencies
conda install pytorch=1.9.1 torchvision cudatoolkit=11.1 -c pytorch -c nvidia

# Install OpenBLAS and OpenEXR
conda install openblas-devel -c anaconda
sudo apt-get install openexr libopenexr-dev
conda install -c conda-forge openexr

# Install Python packages
pip install laspy pytest addict pytorch-metric-learning==0.9.97 yapf==0.40.1 bitarray==1.6.0 h5py transforms3d open3d
pip install tqdm setuptools==59.5.0 einops
pip install bagpy utm pptk

# Install OpenEXR-Python
conda install -c conda-forge openexr-python

# Install PyEXR and PyntCloud
pip install pyexr pyntcloud
```

***The only difference is that when installing openexr-python, I used the following command:***
```bash
conda install -c conda-forge openexr-python
```

Additionally, I used the MinkowskiEngine package from your code repository, version 0.5.4, and installed it as follows:
```bash
cd MinkowskiEngine
python setup.py install --blas_include_dirs=${CONDA_PREFIX}/include --blas=openblas
```

My hardware configuration is as follows:

`GPU: 2xRTX 3090`
`Operating System: Ubuntu 20.04.6 LTS (Focal Fossa)`
`Processor: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz`
`Memory: 64GB`

I followed the instructions precisely and did not make any modifications to the config files. I simply placed [the data](https://drive.google.com/file/d/1rFwfK3LxjMQnzlG_v_73dk63KyphnNjy/view?usp=sharing) into `/crossloc3d/data/` and executed the code using the following command:

```bash
python main.py ./configs/campus_ours.py
```
Subsequently, I encountered the following error message:
`AttributeError: 'MinkowskiConvolution' object has no attribute 'dimension'`

Thank you for your time and kind assistance.

Best regards,

HengDora

**Comment by aswathselvam** [comment]
@HengDora Thanks for mentioning the `openexr-python`, I faced the same issue and resolved using the same method you have mentioned, I will update the steps in readme.

**Comment by HengDora** [comment]
@rayguan97 Thank you very much for your excellent work. Your efforts have been invaluable to the community.

Also, do you have plans to publish [pre-trained models](https://github.com/rayguan97/crossloc3d#evaluation) with the same results as those used in your paper for fair experimentation and evaluation?

Thank you for your time and consideration. I look forward to your response.

Best regards,
HengDora

**Comment by rayguan97** [comment]
Those models are the ones I used in the paper ([link](https://github.com/rayguan97/crossloc3d#checkpoints)), and I'm able to reproduce the numbers in the paper. Are you unable to reproduce similar performance based on those checkpoints?

Best,
Tianrui

**Comment by HengDora** [comment]
After several attempts, I consistently obtained results very similar to those presented in your article, and in some metrics, even better. Here are the results:

| Metric              | Value      |
|:---------------------: |:------------:|
| Recall @ 1%  | 83.0943    |
| Avg. similarity     | 4.6819     |
| Avg. dist           | 67.7905    |
| Avg. recall @ N      | [74.11, 78.82, 81.63, ...]

```bash
2023-10-24 09:14:23,641 - INFO - ====================== EVALUATE RESULTS ======================
2023-10-24 09:14:23,641 - INFO - Sample     Recall@1% 
2023-10-24 09:14:23,641 - INFO - 13         83.0943   
2023-10-24 09:14:23,642 - INFO - Avg. similarity: 4.6819 Avg. dist: 67.7905 Avg. recall @ N:
[74.10762545 78.82497221 81.62649151 83.49889995 85.12053601 86.10804309
 87.20625822 88.29486135 88.92111073 89.68474766 90.10332803 90.6572903
 91.1553117  91.53281449 91.80644047 92.10306387 92.33393721 92.55711529
 92.80603288 93.06099271 93.27605427 93.36468537 93.55354391 93.81852623
 93.97913763]
```

Once again, I'd like to extend my gratitude for your outstanding work and dedication.

Best regards,
HengDora
