### ISSUE TITLE
Failed to load the training_queries_umd_4096.pickle

### ISSUE THREAD

**Issue by Yangrlan** [rayguan97/crossloc3d#2]
Thanks for your great work! I tried to train the model using the campus dataset, but I failed to load the training pickle as it is too large (3GB) . Do you have any ideas about this?

**Comment by rayguan97** [comment]
can you share the exact error? I can't recall running into this issue before.

**Comment by aswathselvam** [comment]
I think it works with a larger RAM, maybe more than 16GB RAM.

**Comment by Yangrlan** [comment]
@rayguan97 I launch the training script and it begins to load the pickle. After a long time the terminal shows "killed", which means that it fails to load the dataset.

**Comment by Yangrlan** [comment]
@aswathselvam I check the RAM size and it is 12GB. It seems that it really requires a larger RAM. Thank you!
